name: ci

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

env:
  IMAGE_NAME: infrabuilder/busybox-trivy-db

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile.trivy-db
          provenance: mode=max
          platform: linux/amd64,linux/arm64,linux/arm/v7
          sbom: true
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}
          cache-to: type=inline
          tags: ${{ steps.meta.outputs.tags }}
